// examples/vue/src/App.vue
<script setup lang="ts">
import { unResolve, unSignal, useIntervalFn } from 'unuse-vue';
import type { Ref } from 'vue';
import { isRef } from 'vue';

const signal = unSignal<string>('Hello, World!');

const resolvedVueRef: Ref<string> = unResolve(signal);

const isVueRef = isRef(resolvedVueRef);

console.log('Resolved Vue Ref:', resolvedVueRef);

const { isActive } = useIntervalFn(() => {
  console.log('Interval function executed', isActive);
}, 1000);
</script>

<template>
  <div class="app">
    <h1>Vue App</h1>
    <p>This is a simple Vue application.</p>
    <p>Signal Value: {{ resolvedVueRef }}</p>
    <p>Is a real Vue Ref: {{ isVueRef ? 'Yes' : 'No' }}</p>
  </div>
</template>

// examples/angular/src/app/app.ts
import type { OnInit, WritableSignal } from '@angular/core';
import { Component, isSignal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import type { UnSignal } from '@unuse/angular';
import { unResolve, unSignal, useIntervalFn } from '@unuse/angular';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.html',
})
export class App implements OnInit {
  signal!: UnSignal<string>;

  resolvedAngularSignal!: WritableSignal<string>;

  isAngularSignal!: boolean;

  ngOnInit(): void {
    this.signal = unSignal<string>('Hello, World!');

    this.resolvedAngularSignal = unResolve(
      this.signal
    ) as unknown as WritableSignal<string>;

    console.log(this.resolvedAngularSignal);

    this.isAngularSignal = isSignal(this.resolvedAngularSignal);

    console.log('Resolved Angular Signal:', this.resolvedAngularSignal());

    const { isActive } = useIntervalFn(() => {
      console.log('Interval function executed', isActive);
    }, 1000);
  }
}
