// examples/vue/src/App.vue
<script setup lang="ts">
import { unResolve, unSignal, useIntervalFn } from 'unuse-vue';
import type { Ref } from 'vue';
import { isRef } from 'vue';

const signal = unSignal<string>('Hello, World!');

const resolvedVueRef: Ref<string> = unResolve(signal);

const isVueRef = isRef(resolvedVueRef);

console.log('Resolved Vue Ref:', resolvedVueRef);

const { isActive } = useIntervalFn(() => {
  console.log('Interval function executed', isActive);
}, 1000);
</script>

<template>
  <div class="app">
    <h1>Vue App</h1>
    <p>This is a simple Vue application.</p>
    <p>Signal Value: {{ resolvedVueRef }}</p>
    <p>Is a real Vue Ref: {{ isVueRef ? 'Yes' : 'No' }}</p>
  </div>
</template>

// examples/solid/src/App.tsx
import type { JSX, Signal } from 'solid-js';
import { unResolve, unSignal, useIntervalFn } from 'unuse-solid';

export default function App(): JSX.Element {
  const signal = unSignal<string>('Hello, World!');

  const resolvedSolidSignal: Signal<string> = unResolve(signal);

  const isSolidSignal = () => typeof resolvedSolidSignal[0] === 'function';

  console.log('Resolved Solid Signal:', resolvedSolidSignal);

  const { isActive } = useIntervalFn(() => {
    console.log('Interval function executed', isActive);
  }, 1000);

  return (
    <div class="app">
      <h1>Solid App</h1>
      <p>This is a simple Solid application.</p>
      <p>Signal Value: {resolvedSolidSignal[0]()}</p>
      <p>Is a real Solid Signal: {isSolidSignal() ? 'Yes' : 'No'}</p>
    </div>
  );
}
