// examples/react/src/App.tsx
import { unResolve, unSignal, useIntervalFn } from 'unuse-react';

export default function App(): React.JSX.Element {
  const signal = unSignal<string>('Hello, World!');

  const resolvedReactState: [
    string | undefined,
    React.Dispatch<React.SetStateAction<string | undefined>>,
  ] = unResolve(signal);

  const isReactState = () => resolvedReactState[0] === 'Hello, World!';

  console.log('Resolved React State:', resolvedReactState);

  const { isActive } = useIntervalFn(() => {
    console.log('Interval function executed', isActive);
  }, 1000);

  return (
    <div className="app">
      <h1>React App</h1>
      <p>This is a simple React application.</p>
      <p>React Value: {resolvedReactState[0]}</p>
      <p>Is a real React State: {isReactState() ? 'Yes' : 'No'}</p>
    </div>
  );
}

// examples/solid/src/App.tsx
import type { JSX, Signal } from 'solid-js';
import { unResolve, unSignal, useIntervalFn } from 'unuse-solid';

export default function App(): JSX.Element {
  const signal = unSignal<string>('Hello, World!');

  const resolvedSolidSignal: Signal<string> = unResolve(signal);

  const isSolidSignal = () => typeof resolvedSolidSignal[0] === 'function';

  console.log('Resolved Solid Signal:', resolvedSolidSignal);

  const { isActive } = useIntervalFn(() => {
    console.log('Interval function executed', isActive);
  }, 1000);

  return (
    <div class="app">
      <h1>Solid App</h1>
      <p>This is a simple Solid application.</p>
      <p>Signal Value: {resolvedSolidSignal[0]()}</p>
      <p>Is a real Solid Signal: {isSolidSignal() ? 'Yes' : 'No'}</p>
    </div>
  );
}
